---
title: "Shiny Application and Reproducible Pitch"
author: "Kalpana Das"
date: "8/4/2020"
output: ioslides_presentation
---

## Introduction
This peer assessed assignment has two parts. First, you will create a Shiny application and deploy it on Rstudio's servers. Second, you will use Slidify or Rstudio Presenter to prepare a reproducible pitch presentation about your application.

- **Shiny Application**: Write a shiny application with associated supporting documentation. Share the application link by pasting it into the provided text box. Share your server.R and ui.R code on github.
- **Reproducible Pitch Presentation**: It must be done in Slidify or Rstudio Presenter, must be 5 pages, must be hosted on github/ Rpubs and must contain some embedded R code that gets run when slidifying the document.

## Comparison of cars
- The shiny app helps compare different cars from the **mtcars** dataset from R. The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models).
- Particular desired features of the car such as Gross horsepower, Transmission, Number of forward gears, Number of cylinders and Engine are selected. The outputed table will then show only the cars with those features. The table can be sorted according to the variable you want by clicking at the arrows at the top of the table.

## Summary of **mtcars** dataset

```{r, echo = TRUE}
summary(mtcars)
```

## Assignment Submission links 

The app developed for the first part of the assignment is avalilable at - 

https://kalpanadas.shinyapps.io/Week_4_Project/

Source code for ui.R and server.R files are available on the GitHub - 

https://github.com/KalpanaDas/Developing-Data-Products-Week-4/


